[package]
name = "holodeck"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
config = "0.14.0"
pixels = "0.13.0"
rand = "0.8.5"
test-case = "3.3.1"
winit = "0.30.3"
